name: hydro-power-prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.6.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - atk-1.0=2.36.0
  - attr=2.5.1
  - attrs=21.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bleach=5.0.1
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.6.15
  - cairo=1.16.0
  - certifi=2022.6.15
  - cffi=1.15.1
  - cryptography=37.0.4
  - cycler=0.11.0
  - cython=0.29.30
  - dbus=1.13.6
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.9.1
  - expat=2.4.8
  - fftw=3.3.10
  - flit-core=3.7.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.34.4
  - freetype=2.10.4
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.8
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.72.1
  - glib-tools=2.72.1
  - graphite2=1.3.13
  - graphviz=5.0.0
  - gst-plugins-base=1.20.3
  - gstreamer=1.20.3
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=5.0.1
  - icu=70.1
  - idna=3.3
  - importlib-metadata=4.11.4
  - importlib_resources=5.9.0
  - ipykernel=6.15.1
  - ipython_genutils=0.2.0
  - jack=1.9.18
  - jedi=0.18.1
  - joblib=1.1.0
  - jpeg=9e
  - jsonschema=4.7.2
  - jupyter_client=7.3.4
  - jupyter_core=4.11.1
  - jupyterlab_pygments=0.2.2
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.64
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.3.3
  - libdb=6.2.32
  - libdeflate=1.12
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.3.4
  - libgcc-ng=12.1.0
  - libgd=2.3.3
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libglib=2.72.1
  - libgomp=12.1.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.20
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=14.4
  - librsvg=2.54.4
  - libsndfile=1.0.31
  - libsodium=1.0.18
  - libstdcxx-ng=12.1.0
  - libtiff=4.4.0
  - libtool=2.4.6
  - libudev1=249
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp=1.2.3
  - libwebp-base=1.2.3
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.14
  - libzlib=1.2.12
  - lightgbm=3.3.2
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - munkres=1.1.4
  - mypy=0.961
  - mypy_extensions=0.4.3
  - mysql-common=8.0.29
  - mysql-libs=8.0.29
  - nbclient=0.6.6
  - nbconvert=6.5.0
  - nbconvert-core=6.5.0
  - nbconvert-pandoc=6.5.0
  - nbformat=5.4.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - notebook=6.4.12
  - nspr=4.32
  - nss=3.78
  - openjpeg=2.4.0
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.4.3
  - pandoc=2.18
  - pandocfilters=1.5.0
  - pango=1.50.8
  - parso=0.8.3
  - patsy=0.5.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pixman=0.40.0
  - ply=3.11
  - pmdarima=1.8.5
  - portaudio=19.6.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.30
  - psutil=5.9.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=14.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.12.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - python=3.10.5
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.1
  - python_abi=3.10
  - pytz=2022.1
  - pyzmq=23.2.0
  - qt-main=5.15.4
  - readline=8.1.2
  - scikit-learn=1.1.1
  - scipy=1.8.1
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - send2trash=1.8.0
  - setuptools=63.2.0
  - sip=6.6.2
  - six=1.16.0
  - soupsieve=2.3.2.post1
  - sqlite=3.39.2
  - stack_data=0.3.0
  - statsmodels=0.13.2
  - terminado=0.15.0
  - threadpoolctl=3.1.0
  - tinycss2=1.1.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - traitlets=5.3.0
  - typing_extensions=4.3.0
  - tzdata=2022a
  - unicodedata2=14.0.0
  - urllib3=1.26.11
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - absl-py==1.2.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - ansiwrap==0.8.4
    - anyio==3.6.1
    - appdirs==1.4.4
    - async-timeout==4.0.2
    - autopep8==1.6.0
    - babel==2.10.3
    - backoff==1.11.1
    - bokbokbok==0.6.1
    - cachetools==5.2.0
    - catboost==1.0.6
    - charset-normalizer==2.1.0
    - click==8.1.3
    - clikit==0.6.2
    - cloudpickle==2.1.0
    - cmdstanpy==1.0.4
    - convertdate==2.4.0
    - crashtest==0.3.1
    - darts==0.20.0
    - dask==2022.7.1
    - debugpy==1.6.2
    - deprecated==1.2.13
    - distributed==2022.7.1
    - ephem==4.1.3
    - frozenlist==1.3.0
    - fsspec==2022.7.0
    - google-auth==2.9.1
    - google-auth-oauthlib==0.4.6
    - greenlet==1.1.2
    - grpcio==1.48.0
    - heapdict==1.0.1
    - hijri-converter==2.2.4
    - holidays==0.14.2
    - httpstan==4.8.1
    - humanize==4.2.3
    - ipdb==0.13.9
    - ipython==7.34.0
    - ipywidgets==7.7.1
    - jinja2==3.0.3
    - json5==0.9.9
    - jupyter==1.0.0
    - jupyter-console==6.4.4
    - jupyter-server==1.18.1
    - jupyterlab==3.4.5
    - jupyterlab-server==2.15.0
    - jupyterlab-widgets==1.1.1
    - jupytext==1.14.0
    - korean-lunar-calendar==0.2.1
    - llvmlite==0.39.0
    - locket==1.0.0
    - lunarcalendar==0.0.9
    - markdown==3.4.1
    - markdown-it-py==2.1.0
    - marshmallow==3.17.0
    - matrixprofile==1.1.10
    - mdit-py-plugins==0.3.0
    - mdurl==0.1.1
    - monotonic==1.6
    - msgpack==1.0.4
    - multidict==6.0.2
    - nbclassic==0.4.3
    - networkx==2.8.5
    - nfoursid==1.0.1
    - notebook-shim==0.1.0
    - numba==0.56.0
    - numpy==1.22.4
    - oauthlib==3.2.0
    - papermill==2.3.4
    - partd==1.2.0
    - pastel==0.2.1
    - pip==22.2.2
    - ploomber==0.19.9
    - ploomber-scaffold==0.3.1
    - plotly==5.9.0
    - posthog==1.4.9
    - prophet==1.1
    - protobuf==3.11.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.8.0
    - pydantic==1.9.1
    - pydeprecate==0.3.2
    - pyflakes==2.4.0
    - pylev==1.4.0
    - pymeeus==0.5.11
    - pysimdjson==3.2.0
    - pystan==3.5.0
    - python-graphviz==0.20.1
    - pytorch-lightning==1.6.5
    - pyyaml==6.0
    - qtconsole==5.3.1
    - qtpy==2.1.0
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - setuptools-git==1.2
    - sktime==0.13.1
    - sniffio==1.2.0
    - sortedcontainers==2.4.0
    - sqlalchemy==1.4.39
    - sqlparse==0.4.2
    - statsforecast==0.7.1
    - stumpy==1.11.1
    - tabulate==0.8.10
    - tbats==1.1.0
    - tblib==1.7.0
    - tenacity==8.0.1
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - textwrap3==0.9.2
    - toolz==0.12.0
    - torch==1.12.0
    - torchmetrics==0.9.3
    - tornado==6.1
    - tqdm==4.64.0
    - tsfresh==0.19.0
    - ujson==5.4.0
    - webargs==8.2.0
    - websocket-client==1.3.3
    - werkzeug==2.2.1
    - widgetsnbextension==3.6.1
    - wrapt==1.14.1
    - xarray==2022.6.0
    - yarl==1.7.2
    - zict==2.2.0
